//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.25 at 09:31:27 PM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://138.201.143.76:80/services")
package com.blito.payments._76._143._201._138._80.services;
